# Generated by Django 5.0.3 on 2024-04-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firtsname',
            new_name='firstname',
        ),
    ]
